name: GitHub Actions Demo
on:
  pull_request:
    types: [opened]

jobs:
  check-description:
    name: Check that PR has description
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is shame-worthy
        run: |
          go run .github/workflows/main.go
        env:
          RAW_BODY: ${{ github.event.pull_request.body }}
          RAW_TITLE: ${{ github.event.pull_request.title }}