name: GitHub Actions Demo
on:
  pull_request:
    types: [opened]

jobs:
  check-description:
    name: Check that PR has description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if PR is shame-worthy
        run: |
          go run .github/workflows/main.go
          echo $RAW_TITLE
          echo $RAW_BODY

        env:
          RAW_TITLE: ${{ github.event.pull_request.title }}
          RAW_BODY: ${{ github.event.pull_request.body }}