on:
  pull_request:
    types: [opened]

jobs:
  check-description:
    name: Check that PR has description
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is shame-worthy
        run: |
          echo $RAW_BODY
        env:
          RAW_BODY: ${{ github.event.pull_request.body }}
