name: hello-world
on:
  pull_request:
    types: [opened]

jobs:
  check-description:
    name: Check that PR has description
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is shame-worthy
        run: |
          echo $RAW_BODY
          echo $RAW_TITLE
        env:
          RAW_BODY: ${{ github.event.pull_request.body }}
          RAW_TITLE: ${{ github.event.pull_request.title }}